from enum import IntEnum


class SocpOpCode(IntEnum):
    READ_CURRENT_SESSION_ID = 0x8c,
    READ_CURRENT_SESSION_ID_RESPONSE = 0x8d,

    GET_SENSOR_DETAILS = 0x90,
    SENSOR_DETAILS_RESPONSE = 0x91

    READ_SESSION_START_TIME = 0x83,
    READ_SESSION_START_TIME_RESPONSE = 0x84,

    # TODO: calibration stuff must be supported by the pump

    # 8c f4b1 (READ_CURRENT_SESSION_ID)
    # 8d 0b a0c1 (READ_CURRENT_SESSION_ID_RESPONSE)

    # 81 fffff9dd (GET_CALIBRATION_CONTEXT)
    # 82 020000f0da (CALIBRATION_CONTEXT_RESPONSE)

    # 90 4962 (GET_SENSOR_DETAILS)
    # 91 071d00ffff60273420 (SENSOR_DETAILS_RESPONSE)

